[project]
name = "polars-workshop"
version = "1.0"
description = "Minimal python env for intro to polars workshop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.1",
    "polars>=1.7.1",
]
